name: Cluster Secrets
description: "A Buildkite plugin to fetch secrets from Buildkite secrets"
author: "@buildkite-plugins"
requirements:
 - bash
 - buildkite-agent
configuration:
  properties:
    key:
      type: string
    variables:
      type: object
additionalProperties: false
